[package]
name = "gravity-wasm"
version = "0.1.0"
authors = ["Roy Adams"]
description = "A gravity simulation tool"
license = "MIT/Apache-2.0"
repository = "https://github.com/rgadams/gravity-wasm"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"